spring:
  datasource:
    url: jdbc:postgresql://ep-wandering-base-atdoywl5-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_VYiIDWgno1H4
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: dummy_username # Replace with Mailtrap username
    password: dummy_password # Replace with Mailtrap password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expirationMs: 86400000 # 24 hours

logging:
  level:
    org.springframework.security: DEBUG
    com.example.lastmile: DEBUG
